version: "3.9"

services:
  hvp-mod15:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: hvp-mod15-notification-service
    ports:
      - "8015:8015"
    environment:
      - HVP_BASE_HOST=http://host.docker.internal
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8015/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - hvp-network

networks:
  hvp-network:
    external: true
    name: hvp-infra-local_hvp-network
